const dict = {
  hi: {
    // Common
    welcome: "स्वागत है...",
    signIn: "लॉग इन करें",
    signUp: "साइन अप करें",
    password: "पासवर्ड",
    otp: "ओटीपी",
    forgot: "पासवर्ड भूल गए?",
    captcha: "कैप्चा",
    captchaPlaceholder: "कैप्चा दर्ज करें",
    usernamePlaceholder: "उपयोगकर्ता नाम",
    passwordPlaceholder: "पासवर्ड",
    signInBtn: "लॉग इन करें",
    checkStatus: "नामांकन स्थिति देखें",
    createNew: "नया खाता बनाएँ",
    details: "पंजीकरण के लिए विवरण भरें",
    continue: "साइन अप जारी रखें",
    // Pages
    goHome: "मुख्य पृष्ठ पर लौटें",

    // Register
    registerHeading: "मानक पंजीकरण",
    registerSub: "हमारे कृषि समुदाय से जुड़ें",
    farmerType: "किसान प्रकार",
    selectFarmer: "किसान का प्रकार चुनें",
    region: "क्षेत्र/जनपद",
    regionPlaceholder: "अपना क्षेत्र या जनपद दर्ज करें",
    finishRegistration: "पंजीकरण पूरा करें",
    firstName: "प्रथम नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    emailPlaceholder: "ईमेल पता दर्ज करें",
    passwordConfirm: "पासवर्ड की पुष्टि करें",
    smallholder: "लघु किसान",
    commercial: "व्यावसायिक किसान",
    cooperative: "सहकारी सदस्य",
    other: "अन्य",
    // RegisterPoor
    poorHeading: "समर्थन कार्यक्रम हेतु पंजीकरण",
    poorSub: "पात्र व्यक्तियों हेतु विशेष पंजीकरण",
    idNumber: "पहचान संख्या",
    idPlaceholder: "राष्ट्रीय पहचान संख्या दर्ज करें",
    address: "पता",
    addressPlaceholder: "अपना पता दर्ज करें",
    phone: "फ़ोन नंबर",
    phonePlaceholder: "फ़ोन नंबर दर्ज करें",
    income: "मासिक आय",
    incomePlaceholder: "मासिक आय दर्ज करें",
    familySize: "परिवार का आकार",
    familySizePlaceholder: "परिवार के सदस्यों की संख्या दर्ज करें",
    submitApplication: "आवेदन सबमिट करें",
    // Home
    homeTitle: "कृषि मित्र",
    homeWelcome: "कृषि मित्र में आपका स्वागत है",
    platformDesc: "कृषि समर्थन, संसाधन वितरण और सामुदायिक सहभागिता के लिए आपका मंच। नीचे दिए गए विकल्पों का उपयोग करके हमारी सेवाओं पर नेविगेट करें।",
    registerPoor: "गरीब लोगों के लिए पंजीकरण",
    poorDesc: "अतिरिक्त सहायता के लिए योग्य लोगों के लिए विशेष पंजीकरण मार्ग।",
    register: "पंजीकरण करें",
    registerDesc: "किसानों और सामुदायिक सदस्यों के लिए मानक पंजीकरण।",
    calendar: "बुवाई कैलेंडर",
    calendarDesc: "मौसमी बोआई गाइड और कृषि कैलेंडर प्राप्त करें।",
    policies: "नीतियाँ",
    policiesDesc: "कृषि नीतियों और सहायता कार्यक्रमों की जानकारी।",
    news: "समाचार",
    newsDesc: "कृषि विकास और सामुदायिक समाचार की ताजा जानकारी।",
    readNews: "समाचार पढ़ें",
    logout: "लॉगआउट",
    userWelcome: "स्वागत है, उपयोगकर्ता",
    copyright: "&copy; 2025 कृषि मित्र. सर्वाधिकार सुरक्षित।",
    // Calendar
    sowingCalendar: "बुवाई कैलेंडर",
    bestPractices: "इष्टतम फसल के लिए मौसमी बुवाई गाइड",
    spring: "वसंत",
    summer: "गर्मी",
    autumn: "पतझड़",
    winter: "सर्दी",
    showCalendar: "कैलेंडर देखें",
    downloadPDF: "कैलेंडर PDF डाउनलोड करें",
    // Policies
    agriPolicies: "कृषि नीतियाँ",
    programInfo: "समर्थन कार्यक्रमों और नियमों की महत्वपूर्ण जानकारी",
    returnPolicy: "मुख्य पृष्ठ पर लौटें",
    downloadPolicy: "नीति दस्तावेज़ डाउनलोड करें",
    // News
    agriNews: "कृषि समाचार",
    newsSub: "कृषि में नवीनतम विकास से अद्यतित रहें",
    latestNews: "नवीनतम समाचार",
    all: "सभी",
    research: "अनुसंधान",
    policy: "नीति",
    market: "बाज़ार",
    program: "कार्यक्रम",
    prev: "पिछला",
    next: "अगला",
    newsletter: "साप्ताहिक अपडेट के लिए हमारे न्यूज़लेटर की सदस्यता लें",
    // 404
    notFound: "अरे! पृष्ठ नहीं मिला",

    // Calendar-specific text
    calendarSpringGuide: "वसंत बुवाई गाइड (मार्च-मई)",
    calendarSpringVeg: "सब्ज़ियाँ",
    calendarSpringCrops: "अनाज",
    calendarSpringVeg1: "टमाटर - प्रारंभिक मार्च (इनडोर बुवाई)",
    calendarSpringVeg2: "मिर्च - मध्य मार्च",
    calendarSpringVeg3: "लेट्यूस - मार्च के अंत से मई",
    calendarSpringVeg4: "गाजर - अप्रैल से",
    calendarSpringVeg5: "फलियाँ - प्रारंभिक मई",
    calendarSpringGrain1: "मक्का - अप्रैल के मध्य से अंत",
    calendarSpringGrain2: "चावल - प्रारंभिक अप्रैल (अंतिम पाला के बाद)",
    calendarSpringGrain3: "गेहूं - मार्च में प्रारंभिक वसंत किस्म",
    calendarSpringGrain4: "जौ - मार्च से अप्रैल",
    calendarSpringTipsTitle: "वसंत बुवाई टिप्स",
    calendarSpringTip1: "अधिकांश वसंत बुवाई के लिए मिट्टी का तापमान 10°C होने की प्रतीक्���ा करें",
    calendarSpringTip2: "बुआई से पहले मिट्टी में कम्पोस्ट और जैविक पदार्थ मिलाएँ",
    calendarSpringTip3: "अंतिम पाले से बचाव के लिए प्रारंभिक बुवाई हेतु रो कवर का उपयोग करें",
    calendarSummerGuide: "ग्रीष्मकालीन बुवाई गाइड (जून-अगस्त)",
    calendarSummerMsg: "ग्रीष्मकालीन बुवाई की जानकारी यहाँ होगी...",
    calendarAutumnGuide: "पतझड़ बुवाई गाइड (सितंबर-नवंबर)",
    calendarAutumnMsg: "पतझड़ बुवाई की जानकारी यहाँ होगी...",
    calendarWinterGuide: "शीतकालीन बुवाई गाइड (दिसंबर-फरवरी)",
    calendarWinterMsg: "शीतकालीन बुवाई की जानकारी यहाँ होगी...",

    // Policies-specific text
    policiesIntro: "यह अनुभाग किसानों के लिए वर्तमान कृषि नीतियों, सब्सिडी और सहायता कार्यक्रमों की जानकारी प्रदान करता है। अधिक जानने के लिए प्रत्येक आइटम पर क्लिक करें।",
    subsidyPrograms: "सब्सिडी कार्यक्रम",
    seedSubsidy: "बीज सब्सिडी कार्यक्रम",
    seedSubsidyDesc: "पंजीकृत किसानों के लिए प्रमाणित बीजों पर 50% सब्सिडी सरकार द्वारा दी जाती है।",
    seedSubsidyEligibility: "पात्रता: 5 हेक्टेयर से कम भूमि वाले सभी लघु किसान।",
    fertilizerAid: "उर्वरक सहायता पहल",
    fertilizerAidDesc: "कृषि विस्तार अधिकारियों के माध्यम से रियायती उर्वरक उपलब्ध हैं।",
    fertilizerAidTime: "वितरण केंद्र सोमवार-शुक्रवार, सुबह 8 से शाम 4 बजे तक खुले हैं।",
    landPolicy: "भूमि उपयोग नीतियाँ",
    landPolicyDesc: "वर्तमान भूमि उपयोग विनियमों, संरक्षण आवश्यकताओं और सतत कृषि पद्धतियों के बारे में जानकारी।",
    waterMgmt: "जल प्रबंधन",
    waterMgmtDesc: "सिंचाई अधिकार, जल संरक्षण तकनीकों और सूखा प्रबंधन रणनीतियों पर दिशानिर्देश।",
    marketAccess: "बाजार पहुँच कार्यक्रम",
    marketAccessDesc: "किसानों को बाजार तक पहुँचने के लिए पहल, जिसमें सहकारी विपणन कार्यक्रम और निर्यात सहायता शामिल हैं।",
    disasterRelief: "आपदा राहत",
    disasterReliefDesc: "फसल विफलता, बाढ़, सूखा या अन्य कृषि आपदाओं की स्थिति में सहायता प्राप्त करने के दिशा-निर्देश।",
    // Add missing About Us and Contact Us translations (Hindi)
    aboutUs: "हमारे बारे में",
    aboutUsText1: "कृषि मित्र किसानों और उनके समुदायों को सुलभ जानकारी, समर्थन और कार्यक्रमों के माध्यम से सशक्त बनाने के लिए समर्पित है। हमारा मिशन आपकी सफलता में मदद करना है!",
    aboutUsText2: "हम प्रौद्योगिकी और ग्रामीण आवश्यकताओं के बीच की खाई को पाटने का प्रयास करते हैं, जिससे प्रत्येक उपयोगकर्ता अपनी पसंदीदा भाषा में हमारी सेवाओं से लाभ उठा सके।",
    contactUs: "संपर्क करें",
    contactUsText: "किसी भी प्रश्न, सहायता या सुझाव के लिए हमसे संपर्क करें:",
    thankYouFeedback: "आपकी प्रतिक्रिया के लिए धन्यवाद!",
    feedbackReceived: "आपकी प्रतिक्रिया सबमिट कर दी गई है।",
    feedback: "प्रतिक्रिया",
    feedbackInfo: "हम आपके विचारों को महत्व देते हैं। कृपया हमें बताएं कि हम कैसे कर रहे हैं!",
    name: "नाम",
    message: "संदेश",
    submit: "सबमिट",
    required: "आवश्यक है",
    // Farming Assistant
    farmingAssistant: "कृषि सहायक",
    chatNow: "अभी चैट करें",
    chatbotDesc: "खेती और कृषि नीतियों के बारे में तुरंत जवाब प्राप्त करें",
    chatbotWelcome: "नमस्ते! मैं आपका कृषि सहायक हूं। भारत में खेती या कृषि नीतियों के बारे में कुछ भी पूछें!",
    thinking: "सोच रहा हूं...",
    askAboutFarming: "खेती के बारे में पूछें...",
  },
  en: {
    // Common
    welcome: "Welcome...",
    signIn: "Sign In",
    signUp: "Sign Up",
    password: "Password",
    otp: "OTP",
    forgot: "Forgot password?",
    captcha: "Captcha",
    captchaPlaceholder: "Enter captcha",
    usernamePlaceholder: "Username",
    passwordPlaceholder: "Password",
    signInBtn: "Sign In",
    checkStatus: "Check Enrollment Status",
    createNew: "Create New Account",
    details: "Fill in the details for registration",
    continue: "Continue Sign Up",

    goHome: "Return to Home",
    // Register
    registerHeading: "Standard Registration",
    registerSub: "Join our agricultural community",
    farmerType: "Farmer Type",
    selectFarmer: "Select farmer type",
    region: "Region/District",
    regionPlaceholder: "Enter your region or district",
    finishRegistration: "Complete Registration",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    emailPlaceholder: "Enter email address",
    passwordConfirm: "Confirm Password",
    smallholder: "Smallholder",
    commercial: "Commercial Farmer",
    cooperative: "Cooperative Member",
    other: "Other",

    poorHeading: "Support Program Registration",
    poorSub: "Special registration for eligible individuals",
    idNumber: "ID Number",
    idPlaceholder: "Enter National ID Number",
    address: "Address",
    addressPlaceholder: "Enter your address",
    phone: "Phone Number",
    phonePlaceholder: "Enter phone number",
    income: "Monthly Income",
    incomePlaceholder: "Enter monthly income",
    familySize: "Family Size",
    familySizePlaceholder: "Enter number of family members",
    submitApplication: "Submit Application",

    // Home
    homeTitle: "Krishi Mitra",
    homeWelcome: "Welcome to Krishi Mitra",
    platformDesc: "Your platform for agricultural support, resource distribution, and community engagement. Use the options below to navigate our services.",
    registerPoor: "Register for Poor",
    poorDesc: "Special registration path for eligible people for additional assistance.",
    register: "Register",
    registerDesc: "Standard registration for farmers and community members.",
    calendar: "Sowing Calendar",
    calendarDesc: "Get seasonal sowing guides and agriculture calendar.",
    policies: "Policies",
    policiesDesc: "View information about agricultural policies and support programs.",
    news: "News",
    newsDesc: "Get the latest on agricultural development and community news.",
    readNews: "Read News",
    logout: "Logout",
    userWelcome: "Welcome, User",
    copyright: "&copy; 2025 Krishi Mitra. All rights reserved.",
    // Calendar
    sowingCalendar: "Sowing Calendar",
    bestPractices: "Seasonal sowing guide for optimal crops",
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    winter: "Winter",
    showCalendar: "View Calendar",
    downloadPDF: "Download Calendar PDF",
    // Policies
    agriPolicies: "Agriculture Policies",
    programInfo: "Important information on support programs and regulations",
    returnPolicy: "Return to Home",
    downloadPolicy: "Download Policy Document",
    // News
    agriNews: "Agriculture News",
    newsSub: "Stay up to date with latest agricultural developments",
    latestNews: "Latest News",
    all: "All",
    research: "Research",
    policy: "Policy",
    market: "Market",
    program: "Program",
    prev: "Prev",
    next: "Next",
    newsletter: "Subscribe to our newsletter for weekly updates",
    // 404
    notFound: "Oops! Page not found",

    // Calendar-specific text (EN)
    calendarSpringGuide: "Spring Sowing Guide (March-May)",
    calendarSpringVeg: "Vegetables",
    calendarSpringCrops: "Grains",
    calendarSpringVeg1: "Tomato - Early March (sow indoors)",
    calendarSpringVeg2: "Chili - Mid March",
    calendarSpringVeg3: "Lettuce - End of March through May",
    calendarSpringVeg4: "Carrot - From April",
    calendarSpringVeg5: "Beans - Early May",
    calendarSpringGrain1: "Maize - Mid to late April",
    calendarSpringGrain2: "Rice - Early April (after last frost)",
    calendarSpringGrain3: "Wheat - Early spring variety in March",
    calendarSpringGrain4: "Barley - March to April",
    calendarSpringTipsTitle: "Spring Sowing Tips",
    calendarSpringTip1: "Wait for soil temperature to reach 10°C for most spring sowings",
    calendarSpringTip2: "Incorporate compost and organic matter before sowing",
    calendarSpringTip3: "Use row covers for early sowing to protect from late frosts",
    calendarSummerGuide: "Summer Sowing Guide (June-August)",
    calendarSummerMsg: "Summer sowing information will appear here...",
    calendarAutumnGuide: "Autumn Sowing Guide (September-November)",
    calendarAutumnMsg: "Autumn sowing information will appear here...",
    calendarWinterGuide: "Winter Sowing Guide (December-February)",
    calendarWinterMsg: "Winter sowing information will appear here...",

    // Policies-specific text (EN)
    policiesIntro: "This section provides information on current agricultural policies, subsidies, and support programs for farmers. Click each item to learn more.",
    subsidyPrograms: "Subsidy Programs",
    seedSubsidy: "Seed Subsidy Program",
    seedSubsidyDesc: "Certified seeds for registered farmers are subsidized at 50% by the government.",
    seedSubsidyEligibility: "Eligibility: All small farmers with less than 5 hectares of land.",
    fertilizerAid: "Fertilizer Aid Initiative",
    fertilizerAidDesc: "Discounted fertilizers are available through agricultural extension officers.",
    fertilizerAidTime: "Distribution centers are open Monday–Friday, 8am–4pm.",
    landPolicy: "Land Use Policies",
    landPolicyDesc: "Information on current land use regulations, conservation requirements, and sustainable farming practices.",
    waterMgmt: "Water Management",
    waterMgmtDesc: "Guidelines on irrigation rights, water conservation techniques, and drought management strategies.",
    marketAccess: "Market Access Programs",
    marketAccessDesc: "Initiatives to help farmers access markets, including cooperative marketing and export support.",
    disasterRelief: "Disaster Relief",
    disasterReliefDesc: "Guidelines for obtaining assistance in case of crop failure, flood, drought, or other agricultural disasters.",
    // Add missing About Us and Contact Us translations (English)
    aboutUs: "About Us",
    aboutUsText1: "Krishi Mitra is dedicated to empowering farmers and their communities through accessible information, support, and programs. Our mission is to help you succeed!",
    aboutUsText2: "We strive to bridge the gap between technology and rural needs, ensuring every user can benefit from our services in their preferred language.",
    contactUs: "Contact Us",
    contactUsText: "For any inquiries, support, or suggestions, contact us at:",
    thankYouFeedback: "Thank you for your feedback!",
    feedbackReceived: "Your feedback has been submitted.",
    feedback: "Feedback",
    feedbackInfo: "We value your thoughts. Please let us know how we're doing!",
    name: "Name",
    message: "Message",
    submit: "Submit",
    required: "is required",
    // Farming Assistant
    farmingAssistant: "Farming Assistant",
    chatNow: "Chat Now",
    chatbotDesc: "Get instant answers about farming and agricultural policies",
    chatbotWelcome: "Hello! I'm your farming assistant. Ask me anything about farming or agricultural policies in India!",
    thinking: "Thinking...",
    askAboutFarming: "Ask about farming...",
  }
};

export function getLang() {
  return localStorage.getItem("lang") || "hi";
}

export function t(key: keyof typeof dict["en"]) {
  const lang = getLang();
  return dict[lang][key] || dict["en"][key] || key;
}

export { dict };
