
const dict = {
  hi: {
    // Common
    welcome: "स्वागत है...",
    signIn: "लॉग इन करें",
    signUp: "साइन अप करें",
    password: "पासवर्ड",
    otp: "ओटीपी",
    forgot: "पासवर्ड भूल गए?",
    captcha: "कैप्चा",
    captchaPlaceholder: "कैप्चा दर्ज करें",
    usernamePlaceholder: "उपयोगकर्ता नाम",
    passwordPlaceholder: "पासवर्ड",
    signInBtn: "लॉग इन करें",
    checkStatus: "नामांकन स्थिति देखें",
    createNew: "नया खाता बनाएँ",
    details: "पंजीकरण के लिए विवरण भरें",
    continue: "साइन अप जारी रखें",
    // Pages
    goHome: "मुख्य पृष्ठ पर लौटें",

    // Register
    registerHeading: "मानक पंजीकरण",
    registerSub: "हमारे कृषि समुदाय से जुड़ें",
    farmerType: "किसान प्रकार",
    selectFarmer: "किसान का प्रकार चुनें",
    region: "क्षेत्र/जनपद",
    regionPlaceholder: "अपना क्षेत्र या जनपद दर्ज करें",
    finishRegistration: "पंजीकरण पूरा करें",
    firstName: "प्रथम नाम",
    lastName: "अंतिम नाम",
    email: "ईमेल",
    emailPlaceholder: "ईमेल पता दर्ज करें",
    passwordConfirm: "पासवर्ड की पुष्टि करें",
    smallholder: "लघु किसान",
    commercial: "व्यावसायिक किसान",
    cooperative: "सहकारी सदस्य",
    other: "अन्य",
    // RegisterPoor
    poorHeading: "समर्थन कार्यक्रम हेतु पंजीकरण",
    poorSub: "पात्र व्यक्तियों हेतु विशेष पंजीकरण",
    idNumber: "पहचान संख्या",
    idPlaceholder: "राष्ट्रीय पहचान संख्या दर्ज करें",
    address: "पता",
    addressPlaceholder: "अपना पता दर्ज करें",
    phone: "फ़ोन नंबर",
    phonePlaceholder: "फ़ोन नंबर दर्ज करें",
    income: "मासिक आय",
    incomePlaceholder: "मासिक आय दर्ज करें",
    familySize: "परिवार का आकार",
    familySizePlaceholder: "परिवार के सदस्यों की संख्या दर्ज करें",
    submitApplication: "आवेदन सबमिट करें",
    // Home
    homeTitle: "सीडहोप कनेक्ट",
    homeWelcome: "सीडहोप कनेक्ट में आपका स्वागत है",
    platformDesc: "कृषि समर्थन, संसाधन वितरण, और सामुदायिक सहभागिता के लिए आपका मंच। नीचे दिए गए विकल्पों का उपयोग करके हमारी सेवाओं पर नेविगेट करें।",
    registerPoor: "गरीब लोगों के लिए पंजीकरण",
    poorDesc: "अतिरिक्त सहायता के लिए योग्य लोगों के लिए विशेष पंजीकरण मार्ग।",
    register: "पंजीकरण करें",
    registerDesc: "किसानों और सामुदायिक सदस्यों के लिए मानक पंजीकरण।",
    calendar: "बुवाई कैलेंडर",
    calendarDesc: "मौसमी बोआई गाइड और कृषि कैलेंडर प्राप्त करें।",
    policies: "नीतियाँ",
    policiesDesc: "कृषि नीतियों और सहायता कार्यक्रमों की जानकारी।",
    news: "समाचार",
    newsDesc: "कृषि विकास और सामुदायिक समाचार की ताजा जानकारी।",
    readNews: "समाचार पढ़ें",
    logout: "लॉगआउट",
    userWelcome: "स्वागत है, उपयोगकर्ता",
    copyright: "&copy; 2025 सीडहोप कनेक्ट. सर्वाधिकार सुरक्षित।",
    // Calendar
    sowingCalendar: "बुवाई कैलेंडर",
    bestPractices: "इष्टतम फसल के लिए मौसमी बुवाई गाइड",
    spring: "वसंत",
    summer: "गर्मी",
    autumn: "पतझड़",
    winter: "सर्दी",
    showCalendar: "कैलेंडर देखें",
    downloadPDF: "कैलेंडर PDF डाउनलोड करें",
    // Policies
    agriPolicies: "कृषि नीतियाँ",
    programInfo: "समर्थन कार्यक्रमों और नियमों की महत्वपूर्ण जानकारी",
    returnPolicy: "मुख्य पृष्ठ पर लौटें",
    downloadPolicy: "नीति दस्तावेज़ डाउनलोड करें",
    // News
    agriNews: "कृषि समाचार",
    newsSub: "कृषि में नवीनतम विकास से अद्यतित रहें",
    latestNews: "नवीनतम समाचार",
    all: "सभी",
    research: "अनुसंधान",
    policy: "नीति",
    market: "बाज़ार",
    program: "कार्यक्रम",
    prev: "पिछला",
    next: "अगला",
    newsletter: "साप्ताहिक अपडेट के लिए हमारे न्यूज़लेटर की सदस्यता लें",
    // 404
    notFound: "अरे! पृष्ठ नहीं मिला"
  },
  en: {
    // Common
    welcome: "Welcome...",
    signIn: "Sign In",
    signUp: "Sign Up",
    password: "Password",
    otp: "OTP",
    forgot: "Forgot password?",
    captcha: "Captcha",
    captchaPlaceholder: "Enter captcha",
    usernamePlaceholder: "Username",
    passwordPlaceholder: "Password",
    signInBtn: "Sign In",
    checkStatus: "Check Enrollment Status",
    createNew: "Create New Account",
    details: "Fill in the details for registration",
    continue: "Continue Sign Up",

    goHome: "Return to Home",
    // Register
    registerHeading: "Standard Registration",
    registerSub: "Join our agricultural community",
    farmerType: "Farmer Type",
    selectFarmer: "Select farmer type",
    region: "Region/District",
    regionPlaceholder: "Enter your region or district",
    finishRegistration: "Complete Registration",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    emailPlaceholder: "Enter email address",
    passwordConfirm: "Confirm Password",
    smallholder: "Smallholder",
    commercial: "Commercial Farmer",
    cooperative: "Cooperative Member",
    other: "Other",

    poorHeading: "Support Program Registration",
    poorSub: "Special registration for eligible individuals",
    idNumber: "ID Number",
    idPlaceholder: "Enter National ID Number",
    address: "Address",
    addressPlaceholder: "Enter your address",
    phone: "Phone Number",
    phonePlaceholder: "Enter phone number",
    income: "Monthly Income",
    incomePlaceholder: "Enter monthly income",
    familySize: "Family Size",
    familySizePlaceholder: "Enter number of family members",
    submitApplication: "Submit Application",

    // Home
    homeTitle: "SeedHope Connect",
    homeWelcome: "Welcome to SeedHope Connect",
    platformDesc: "Your platform for agricultural support, resource distribution, and community engagement. Use the options below to navigate our services.",
    registerPoor: "Register for Poor",
    poorDesc: "Special registration path for eligible people for additional assistance.",
    register: "Register",
    registerDesc: "Standard registration for farmers and community members.",
    calendar: "Sowing Calendar",
    calendarDesc: "Get seasonal sowing guides and agriculture calendar.",
    policies: "Policies",
    policiesDesc: "View information about agricultural policies and support programs.",
    news: "News",
    newsDesc: "Get the latest on agricultural development and community news.",
    readNews: "Read News",
    logout: "Logout",
    userWelcome: "Welcome, User",
    copyright: "&copy; 2025 SeedHope Connect. All rights reserved.",
    // Calendar
    sowingCalendar: "Sowing Calendar",
    bestPractices: "Seasonal sowing guide for optimal crops",
    spring: "Spring",
    summer: "Summer",
    autumn: "Autumn",
    winter: "Winter",
    showCalendar: "View Calendar",
    downloadPDF: "Download Calendar PDF",
    // Policies
    agriPolicies: "Agriculture Policies",
    programInfo: "Important information on support programs and regulations",
    returnPolicy: "Return to Home",
    downloadPolicy: "Download Policy Document",
    // News
    agriNews: "Agriculture News",
    newsSub: "Stay up to date with latest agricultural developments",
    latestNews: "Latest News",
    all: "All",
    research: "Research",
    policy: "Policy",
    market: "Market",
    program: "Program",
    prev: "Prev",
    next: "Next",
    newsletter: "Subscribe to our newsletter for weekly updates",
    //404
    notFound: "Oops! Page not found"
  }
};

export function getLang() {
  return localStorage.getItem("lang") || "hi";
}

export function t(key: keyof typeof dict["en"]) {
  const lang = getLang();
  return dict[lang][key] || dict["en"][key] || key;
}

export { dict };
